version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - .:/home/appdev/src
      - C:/Path/To/Data/Dir/data:/home/appdev/data
    restart: unless-stopped
    command: tail -f /dev/null
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]